### ISSUE TITLE
推流停止后，hls文件没有清理

### ISSUE THREAD

**Issue by ajaxhe** [avplus/srs#7]
停止推流后（停止1小时后），forwad模块没有清理历史ts文件
-rw-r--r-- 1 root    root  5810704 Jan 20 10:15 test-3151.ts
-rw-r--r-- 1 root    root  5769344 Jan 20 10:16 test-3152.ts
-rw-r--r-- 1 root    root  5812020 Jan 20 10:16 test-3153.ts
-rw-r--r-- 1 root    root  5513100 Jan 20 10:16 test-3154.ts
-rw-r--r-- 1 root    root  3268192 Jan 20 10:16 test-3155.ts
-rw-r--r-- 1 root    root      284 Jan 20 10:16 test.m3u8

**Comment by Himer** [comment]
hls {
        hls_dispose 40;
    }

添加逻辑：如果没有配置此项 则10分钟后清理
